In [4]:
import numpy

In [5]:
import numpy as np

In [6]:
#Crear una matriz de 3x3 con valores de 0 a 8

In [7]:
p = np.arange(0,9)

In [8]:
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
np.resize(p,(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
#Crear una matriz de identidad de 6x6

In [12]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])