In [7]:
import numpy

In [9]:
import numpy as np

In [1]:
#Crear un vector o matriz de una dimensión, con valores dentro del rango 3 a el número que representa tu edad

In [22]:
v1=np.array(range(3,26))

In [23]:
v1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25])

In [2]:
#Crear un arreglo con los siguientes elementos [0,1,2,3,4,0,1,2,3,4]

In [24]:
v2=numpy.array([0,1,2,3,4,0,1,2,3,4])

In [25]:
type(v2)

numpy.ndarray

In [26]:
v2

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [3]:
#Ordena de forma ascendiente dicho rango

In [27]:
v2.sort()

In [28]:
v2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])